// 這個檔案是根據您提供的 Relay 資料夾自動生成的繼電器資料庫。
const RELAY_DATA = {
    "2C": {
        "name": "2C 電驛",
        "drawingElements": [
            { "id": 38, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 45, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 46, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 47, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 48, "type": "connector", "x": 540, "y": 180, "label": "" },
            { "id": 49, "type": "rect", "x": 460, "y": 80, "width": 100, "height": 120 },
            { "id": 51, "type": "circle", "x": 510, "y": 140, "radius": 20 },
            { "id": 56, "type": "text", "x": 490, "y": 60, "content": "PR(X)", "font": "16px sans-serif" },
            { "id": 57, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 58, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 59, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 60, "type": "text", "x": 470, "y": 90, "content": "2", "font": "16px sans-serif" },
            { "id": 61, "type": "text", "x": 490, "y": 90, "content": "1", "font": "16px sans-serif" },
            { "id": 62, "type": "text", "x": 530, "y": 90, "content": "7", "font": "16px sans-serif" },
            { "id": 63, "type": "text", "x": 510, "y": 90, "content": "8", "font": "16px sans-serif" },
            { "id": 64, "type": "text", "x": 470, "y": 190, "content": "3", "font": "16px sans-serif" },
            { "id": 65, "type": "text", "x": 490, "y": 190, "content": "4", "font": "16px sans-serif" },
            { "id": 66, "type": "text", "x": 510, "y": 190, "content": "5", "font": "16px sans-serif" },
            { "id": 67, "type": "text", "x": 530, "y": 190, "content": "6", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "a-contact", "connectors": [45, 58] },
            { "type": "b-contact", "connectors": [46, 58] },
            { "type": "a-contact", "connectors": [48, 59] },
            { "type": "b-contact", "connectors": [47, 59] },
            { "type": "coil", "connectors": [38, 57] }
        ]
    },
    "3C": {
        "name": "3C 電驛",
        "drawingElements": [
            { "id": 38, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 40, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 41, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 45, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 46, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 47, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 48, "type": "connector", "x": 540, "y": 180, "label": "" },
            { "id": 49, "type": "rect", "x": 460, "y": 80, "width": 100, "height": 120 },
            { "id": 51, "type": "circle", "x": 510, "y": 140, "radius": 20 },
            { "id": 52, "type": "connector", "x": 540, "y": 120, "label": "" },
            { "id": 53, "type": "connector", "x": 480, "y": 120, "label": "" },
            { "id": 54, "type": "connector", "x": 480, "y": 160, "label": "" },
            { "id": 55, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 56, "type": "text", "x": 490, "y": 60, "content": "PR(X)", "font": "16px sans-serif" },
            { "id": 57, "type": "text", "x": 490, "y": 87, "content": "1", "font": "16px sans-serif" },
            { "id": 58, "type": "text", "x": 470, "y": 87, "content": "2", "font": "16px sans-serif" },
            { "id": 59, "type": "text", "x": 550, "y": 87, "content": "10", "font": "16px sans-serif" },
            { "id": 60, "type": "text", "x": 510, "y": 87, "content": "11", "font": "16px sans-serif" },
            { "id": 61, "type": "text", "x": 470, "y": 110, "content": "3", "font": "16px sans-serif" },
            { "id": 62, "type": "text", "x": 550, "y": 110, "content": "9", "font": "16px sans-serif" },
            { "id": 63, "type": "text", "x": 470, "y": 150, "content": "4", "font": "16px sans-serif" },
            { "id": 64, "type": "text", "x": 470, "y": 192, "content": "5", "font": "16px sans-serif" },
            { "id": 65, "type": "text", "x": 490, "y": 192, "content": "6", "font": "16px sans-serif" },
            { "id": 66, "type": "text", "x": 550, "y": 192, "content": "8", "font": "16px sans-serif" },
            { "id": 67, "type": "text", "x": 520, "y": 192, "content": "7", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "a-contact", "connectors": [40, 54] },
            { "type": "b-contact", "connectors": [40, 45] },
            { "type": "a-contact", "connectors": [46, 53] },
            { "type": "b-contact", "connectors": [47, 53] },
            { "type": "a-contact", "connectors": [52, 55] },
            { "type": "b-contact", "connectors": [48, 55] },
            { "type": "coil", "connectors": [38, 41] }
        ]
    },
    "4C": {
        "name": "4C 電驛",
        "drawingElements": [
            { "id": 1, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 2, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 3, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 4, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 9, "type": "connector", "x": 540, "y": 80, "label": "" },
            { "id": 10, "type": "connector", "x": 520, "y": 80, "label": "" },
            { "id": 11, "type": "connector", "x": 500, "y": 80, "label": "" },
            { "id": 13, "type": "connector", "x": 540, "y": 160, "label": "" },
            { "id": 14, "type": "connector", "x": 520, "y": 160, "label": "" },
            { "id": 16, "type": "connector", "x": 480, "y": 160, "label": "" },
            { "id": 17, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 18, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 19, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 20, "type": "rect", "x": 460, "y": 60, "width": 100, "height": 140 },
            { "id": 23, "type": "line", "x1": 480, "y1": 120, "x2": 490, "y2": 120 },
            { "id": 26, "type": "line", "x1": 500, "y1": 120, "x2": 510, "y2": 120 },
            { "id": 27, "type": "line", "x1": 520, "y1": 120, "x2": 530, "y2": 120 },
            { "id": 28, "type": "line", "x1": 540, "y1": 120, "x2": 550, "y2": 120 },
            { "id": 29, "type": "line", "x1": 480, "y1": 140, "x2": 490, "y2": 140 },
            { "id": 30, "type": "line", "x1": 500, "y1": 140, "x2": 510, "y2": 140 },
            { "id": 31, "type": "line", "x1": 520, "y1": 140, "x2": 530, "y2": 140 },
            { "id": 32, "type": "line", "x1": 540, "y1": 140, "x2": 550, "y2": 140 },
            { "id": 33, "type": "line", "x1": 630, "y1": 120, "x2": 630, "y2": 120 },
            { "id": 34, "type": "text", "x": 500, "y": 30, "content": "PR(X)", "font": "16px sans-serif" },
            { "id": 37, "type": "connector", "x": 500, "y": 160, "label": "" },
            { "id": 38, "type": "text", "x": 490, "y": 70, "content": "3", "font": "16px sans-serif" },
            { "id": 39, "type": "text", "x": 510, "y": 70, "content": "2", "font": "16px sans-serif" },
            { "id": 40, "type": "text", "x": 530, "y": 70, "content": "1", "font": "16px sans-serif" },
            { "id": 41, "type": "text", "x": 530, "y": 100, "content": "5", "font": "16px sans-serif" },
            { "id": 42, "type": "text", "x": 510, "y": 100, "content": "6", "font": "16px sans-serif" },
            { "id": 43, "type": "text", "x": 490, "y": 100, "content": "7", "font": "16px sans-serif" },
            { "id": 44, "type": "text", "x": 470, "y": 100, "content": "8", "font": "16px sans-serif" },
            { "id": 45, "type": "text", "x": 540, "y": 175, "content": "9", "font": "16px sans-serif" },
            { "id": 46, "type": "text", "x": 510, "y": 150, "content": "10", "font": "16px sans-serif" },
            { "id": 47, "type": "text", "x": 490, "y": 150, "content": "11", "font": "16px sans-serif" },
            { "id": 48, "type": "text", "x": 470, "y": 150, "content": "12", "font": "16px sans-serif" },
            { "id": 49, "type": "text", "x": 470, "y": 190, "content": "4", "font": "16px sans-serif" },
            { "id": 50, "type": "text", "x": 490, "y": 190, "content": "14", "font": "16px sans-serif" },
            { "id": 51, "type": "text", "x": 510, "y": 190, "content": "13", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "a-contact", "connectors": [4, 13] },
            { "type": "b-contact", "connectors": [9, 13] },
            { "type": "a-contact", "connectors": [3, 14] },
            { "type": "b-contact", "connectors": [10, 14] },
            { "type": "a-contact", "connectors": [2, 37] },
            { "type": "b-contact", "connectors": [11, 37] },
            { "type": "a-contact", "connectors": [1, 16] },
            { "type": "b-contact", "connectors": [16, 19] },
            { "type": "coil", "connectors": [17, 18] }
        ]
    },
    "ON-delay": {
        "name": "ON-delay 限時電驛",
        "drawingElements": [
            { "id": 45, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 47, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 48, "type": "connector", "x": 540, "y": 180, "label": "" },
            { "id": 49, "type": "rect", "x": 460, "y": 80, "width": 100, "height": 120 },
            { "id": 56, "type": "text", "x": 490, "y": 60, "content": "TR(X)", "font": "16px sans-serif" },
            { "id": 57, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 60, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 61, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 62, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 64, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 65, "type": "knob", "x": 510, "y": 140, "radius": 30, "value": 0, "maxValue": 10 },
            { "id": 66, "type": "text", "x": 470, "y": 90, "content": "6", "font": "16px sans-serif" },
            { "id": 67, "type": "text", "x": 490, "y": 90, "content": "5", "font": "16px sans-serif" },
            { "id": 68, "type": "text", "x": 510, "y": 90, "content": "4", "font": "16px sans-serif" },
            { "id": 69, "type": "text", "x": 530, "y": 90, "content": "3", "font": "16px sans-serif" },
            { "id": 70, "type": "text", "x": 530, "y": 190, "content": "2", "font": "16px sans-serif" },
            { "id": 71, "type": "text", "x": 510, "y": 190, "content": "1", "font": "16px sans-serif" },
            { "id": 72, "type": "text", "x": 470, "y": 190, "content": "7", "font": "16px sans-serif" },
            { "id": 73, "type": "text", "x": 490, "y": 190, "content": "8", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "a-contact", "connectors": [47, 62] },
            { "type": "b-contact", "connectors": [47, 61] },
            { "type": "coil", "connectors": [45, 48] },
            { "type": "timed-a-contact", "connectors": [57, 64], "knobId": 63 },
            { "type": "timed-b-contact", "connectors": [60, 64], "knobId": 63 }
        ]
    },
    "Y-delta-27": {
        "name": "Y-Δ 限時27電驛",
        "drawingElements": [
            { "id": 45, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 47, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 49, "type": "rect", "x": 460, "y": 80, "width": 100, "height": 120 },
            { "id": 56, "type": "text", "x": 490, "y": 60, "content": "TR-Δ(X)", "font": "16px sans-serif" },
            { "id": 64, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 66, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 68, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 70, "type": "connector", "x": 540, "y": 180, "label": "" },
            { "id": 71, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 72, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 73, "type": "knob", "x": 510, "y": 140, "radius": 30, "value": 0, "maxValue": 10 },
            { "id": 74, "type": "text", "x": 510, "y": 190, "content": "1", "font": "16px sans-serif" },
            { "id": 75, "type": "text", "x": 530, "y": 190, "content": "2", "font": "16px sans-serif" },
            { "id": 76, "type": "text", "x": 530, "y": 90, "content": "3", "font": "16px sans-serif" },
            { "id": 77, "type": "text", "x": 510, "y": 90, "content": "4", "font": "16px sans-serif" },
            { "id": 78, "type": "text", "x": 490, "y": 90, "content": "5", "font": "16px sans-serif" },
            { "id": 79, "type": "text", "x": 470, "y": 90, "content": "6", "font": "16px sans-serif" },
            { "id": 80, "type": "text", "x": 470, "y": 190, "content": "7", "font": "16px sans-serif" },
            { "id": 81, "type": "text", "x": 490, "y": 190, "content": "8", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "coil", "connectors": [45, 70] },
            { "type": "a-contact", "connectors": [47, 72] },
            { "type": "timed-a-contact", "connectors": [64, 71], "knobId": 73 },
            { "type": "timed-b-contact", "connectors": [64, 66], "knobId": 73 }
        ]
    },
    "Y-delta-28": {
        "name": "Y-Δ 限時28電驛",
        "drawingElements": [
            { "id": 45, "type": "connector", "x": 480, "y": 180, "label": "" },
            { "id": 47, "type": "connector", "x": 520, "y": 180, "label": "" },
            { "id": 49, "type": "rect", "x": 460, "y": 80, "width": 100, "height": 120 },
            { "id": 56, "type": "text", "x": 490, "y": 60, "content": "TR-Δ(X)", "font": "16px sans-serif" },
            { "id": 64, "type": "connector", "x": 500, "y": 180, "label": "" },
            { "id": 73, "type": "knob", "x": 510, "y": 140, "radius": 30, "value": 0, "maxValue": 10 },
            { "id": 74, "type": "connector", "x": 540, "y": 180, "label": "" },
            { "id": 75, "type": "connector", "x": 480, "y": 100, "label": "" },
            { "id": 76, "type": "connector", "x": 500, "y": 100, "label": "" },
            { "id": 77, "type": "connector", "x": 520, "y": 100, "label": "" },
            { "id": 78, "type": "connector", "x": 540, "y": 100, "label": "" },
            { "id": 79, "type": "text", "x": 510, "y": 190, "content": "1", "font": "16px sans-serif" },
            { "id": 80, "type": "text", "x": 530, "y": 190, "content": "2", "font": "16px sans-serif" },
            { "id": 81, "type": "text", "x": 530, "y": 90, "content": "3", "font": "16px sans-serif" },
            { "id": 82, "type": "text", "x": 510, "y": 90, "content": "4", "font": "16px sans-serif" },
            { "id": 83, "type": "text", "x": 490, "y": 90, "content": "5", "font": "16px sans-serif" },
            { "id": 84, "type": "text", "x": 470, "y": 90, "content": "6", "font": "16px sans-serif" },
            { "id": 85, "type": "text", "x": 470, "y": 190, "content": "7", "font": "16px sans-serif" },
            { "id": 86, "type": "text", "x": 490, "y": 190, "content": "8", "font": "16px sans-serif" }
        ],
        "componentFunctions": [
            { "type": "coil", "connectors": [64, 74] },
            { "type": "a-contact", "connectors": [45, 64] },
            { "type": "timed-a-contact", "connectors": [76, 77], "knobId": 73 },
            { "type": "timed-b-contact", "connectors": [75, 77], "knobId": 73 }
        ]
    }
};

